# baseURL = "https://reaganlandsurveying.com/"
baseURL = "https://ajsmith607.github.io/rls/"
languageCode = "en-us"
title = "Reagan Land Surveying"
publishDir = "docs" 
enableGitInfo = true
footnoteReturnLinkContents = "↩"
lastmod = [":fileModTime", ":default"] # auto populates lastmod date
paginate = "50"

[params]
  _merge = "deep"
  #analyticsid = ""
  #additionalmetatags = "<meta name=\"msvalidate.01\" content=\"\" />" 
  
# theming and reusable code
[module]
  _merge = "deep"
  [[module.imports]]
    path = "github.com/ajsmith607/undergo"
 
[markup]
  _merge = "deep"
